package.json, src/components/TextBoxField/__stories__/index.stories.tsx, src/components/TextBoxField/__tests__/__snapshots__/index.spec.tsx.snap, src/components/TextBoxField/__tests__/index.spec.tsx, src/components/TextBoxField/index.tsx, src/helpers/pickValidators.ts, src/mocks/mockErrors.ts, src/providers/ErrorContext/__tests__/index.spec.tsx, src/providers/ErrorContext/index.tsx, src/types.ts, src/validators/__tests__/max.spec.ts, src/validators/__tests__/maxLength.spec.ts, src/validators/__tests__/min.spec.ts, src/validators/__tests__/minLength.spec.ts, src/validators/__tests__/regex.spec.ts, src/validators/index.ts, src/validators/max.ts, src/validators/maxLength.ts, src/validators/min.ts, src/validators/minLength.ts, src/validators/regex.ts, src/validators/types.ts, yarn.lock
- Feature
Import TextBoxField from our console repo
1. Add TextBoxField
2. Stories
3. Tests
=> feat: add textbox field

src/components/Form/index.tsx, src/components/SwitchField/index.tsx, src/components/TextBoxField/index.tsx, src/index.ts, src/providers/ErrorContext/index.tsx
- Enhancement
1. Add custom error string directly instead of error object (more compatibility with older behaviour)
2. Add custom render
3. Add custom className (styled compatibility)
=> feat: add classnames, custom render and custom error strings

package.json, src/components/Form/index.tsx, yarn.lock
- Enhancement
Add Focus Decorator
=> feat: add focus error decorator

package.json, yarn.lock
Reverts scaleway/scaleway-form#57
=> Revert "chore(devdeps): update semantic-release monorepo (major)"

src/components/CheckboxField/__stories__/index.stories.tsx, src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap, src/components/CheckboxField/__tests__/index.spec.tsx, src/components/CheckboxField/index.tsx, src/helpers/pickValidators.ts
- Feature
Migrate TextboxField from the console
=> feat: add CheckboxField

.github/renovate.json
=> ci(renovate): widen engine

src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap, src/components/CheckboxField/__tests__/index.spec.tsx, src/components/CheckboxField/index.tsx, src/providers/ErrorContext/__tests__/index.spec.tsx
- Enhancement
Improves code coverage and fixes some things
(Describe what you did)
1. Change useField to match checkbox type requirements
2. Add more tests to have 100% coverage
=> fix: improves coverage for checkbox field

.storybook/preview.tsx, package.json, src/components/CheckboxField/__stories__/index.stories.tsx, src/components/CheckboxField/index.tsx, src/components/Form/__tests__/index.spec.tsx, src/components/RadioBorderedBoxField/__stories__/index.stories.tsx, src/components/RadioBorderedBoxField/index.tsx, src/components/RadioField/__stories__/index.stories.tsx, src/components/RadioField/index.tsx, src/components/Submit/__stories__/index.stories.tsx, src/components/Submit/__tests__/index.spec.tsx, src/components/SwitchField/__stories__/index.stories.tsx, src/components/SwitchField/index.tsx, src/components/TextBoxField/__stories__/index.stories.tsx, src/components/TextBoxField/index.tsx, yarn.lock
Code cohesion with other projects 
- Enhancement
=> chore: code cleanup

src/components/Form/__tests__/index.spec.tsx, src/components/Submit/__stories__/index.stories.tsx, src/components/Submit/__tests__/index.spec.tsx, src/components/SubmitErrorAlert/__stories__/index.stories.tsx, src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap, src/components/SubmitErrorAlert/__tests__/index.spec.tsx, src/components/SubmitErrorAlert/index.tsx
Was named FormErrorAlert
- Feature
=> feat: new SubmitErrorAlert

src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap, src/components/Submit/__tests__/index.spec.tsx, src/components/Submit/index.tsx, src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap
=> fix: allow to resubmit if submitError is not related to validation

package.json, src/components/TagsField/__stories__/index.stories.tsx, src/components/TagsField/__tests__/__snapshots__/index.spec.tsx.snap, src/components/TagsField/__tests__/index.spec.tsx, src/components/TagsField/index.tsx, yarn.lock
- Feature
Add Tags Field Component
1. Migrate Tags Field
=> feat(tags): add Tags Field

src/components/StepperField/__stories__/index.stories.tsx, src/components/StepperField/__tests__/__snapshots__/index.spec.tsx.snap, src/components/StepperField/__tests__/index.spec.tsx, src/components/StepperField/index.tsx
=> feat(stepper): add stepper field

.github/renovate.json
=> chore(renovate): upgrade renovate config managers

package.json, src/components/CheckboxField/index.tsx, src/components/RadioBorderedBoxField/index.tsx, src/components/RadioField/index.tsx, src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap, src/components/SwitchField/__tests__/__snapshots__/index.spec.tsx.snap, src/components/SwitchField/index.tsx, src/components/TagsField/__tests__/__snapshots__/index.spec.tsx.snap, src/components/TextBoxField/index.tsx, yarn.lock
- Refactor
Add default handler for events ( onChange, onFocus, onBlur) 
use type from component and avoid rewrite of type
sort type props
PS: this will allow us to easily see which props is missing on scaleway-ui component 
exemple for required, which is not set up on all component actually
=> fix(components): add default handler props and sort props & type

.github/workflows/teardown_pull_request.yml
=> ci(teardown): fix image name

src/components/RichSelectField/index.tsx
- Enhancement
Add missing type  to RichSelectField from RichSelect
=> fix(rich-select): add missing type

.prettierignore, src/components/CheckboxField/__stories__/index.stories.tsx, src/components/RadioBorderedBoxField/__stories__/index.stories.tsx, src/components/RadioBorderedBoxField/__tests__/index.spec.tsx, src/components/Submit/__stories__/index.stories.tsx, src/components/Submit/__tests__/index.spec.tsx, src/components/Submit/index.tsx, src/components/SubmitErrorAlert/__tests__/index.spec.tsx, src/components/SubmitErrorAlert/index.tsx, src/components/SwitchField/__stories__/index.stories.tsx, src/components/TextBoxField/__stories__/index.stories.tsx, src/mocks/mockErrors.ts, src/types.ts
- Style : Format all project with prettier
=> style(format): format all project

.storybook/preview.tsx
=> chore: correct theme in storybook

src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap, src/components/CheckboxField/__tests__/index.spec.tsx, src/components/CheckboxField/index.tsx
- Bug
touched instead of dirty
=> fix: touched instead of dirty

.github/workflows/ci.yml, .github/workflows/deploy_storybook.yml, .github/workflows/pull_request_title.yml, .github/workflows/teardown_pull_request.yml
=> ci(node): upgrade to node 18

src/components/TextBoxField/index.tsx
- Enhancement
Add a random props forward to TextBox
=> feat(textbox): add random

package.json, pnpm-lock.yaml, src/components/RadioBorderedBoxField/__tests__/__snapshots__/index.spec.tsx.snap, src/components/RadioBorderedBoxField/index.tsx, src/components/RadioField/__tests__/__snapshots__/index.spec.tsx.snap, src/components/RadioField/__tests__/index.spec.tsx, src/components/RadioField/index.tsx, src/components/TagsField/__tests__/__snapshots__/index.spec.tsx.snap
- Migration
- Refactor
No more valid attribute on Radio, thanks to acceptability attributes we use now on Radio like `aria-invalid`, `aria-disabled` & `aria-checked` 
(Describe what you did)
1. Remove valid attribute from Radio field
=> fix: migration to updated Radio from scw-ui

package.json, pnpm-lock.yaml, src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap, src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap
- Bug
- Feature
- Enhancement
- Documentation
- Migration
- Refactor
(Description of the new behavior)
(Describe what you did)
1.
2.
3.
Page | Before | After
:-   |  :-:   | -:
url | screenshot | screenshot
url | screenshot | screenshot
=> chore(deps): update scw-ui

package.json, pnpm-lock.yaml, src/components/RadioBorderedBoxField/__tests__/__snapshots__/index.spec.tsx.snap, src/components/RadioField/__tests__/index.spec.tsx, src/components/SelectableCardField/__stories__/index.stories.tsx, src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap, src/components/SelectableCardField/__tests__/index.spec.tsx, src/components/SelectableCardField/index.tsx
- Feature
New SelectableCardField from Scaleway UI.
=> feat: new SelectableCardField

src/index.ts
=> fix: add export of selectablecardfield

package.json, pnpm-lock.yaml, src/components/DateField/__tests__/__snapshots__/index.tsx.snap, src/components/RadioBorderedBoxField/__tests__/__snapshots__/index.spec.tsx.snap, src/components/RadioField/__tests__/__snapshots__/index.spec.tsx.snap, src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap, src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap, src/components/TextBoxField/__tests__/__snapshots__/index.spec.tsx.snap
=> fix: update scaleway ui v0.178.3

src/components/SelectableCardField/index.tsx
=> fix(SelectableCard): add missing tooltip prop

package.json, pnpm-lock.yaml, src/components/DateField/__tests__/__snapshots__/index.tsx.snap
Update SCW-UI. Fixes storybook's blank pages
- Bug
=> chore: update scw-ui

package.json
- Enhancement
(Description of the new behavior)
(Describe what you did)
1.
2.
3.
Page | Before | After
:-   |  :-:   | -:
url | screenshot | screenshot
url | screenshot | screenshot
=> chore(pnpm): update version

src/components/TextBoxField/index.tsx
- Enhancement
forward props resizable, fillAvailable
=> fix(text-box): add resizable,fillAvailable props

package.json, pnpm-lock.yaml, src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap, src/components/CheckboxField/__tests__/index.spec.tsx, src/components/CheckboxField/index.tsx, src/components/RadioField/__tests__/__snapshots__/index.spec.tsx.snap, src/components/RadioField/__tests__/index.spec.tsx, src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap, src/components/SelectableCardField/__tests__/index.spec.tsx, src/components/SelectableCardField/index.tsx
Upgrade scaleway ui including new props for SelectableCard and update of Radio and Checkbox.
=> fix: update scaleway ui

src/components/TextBoxField/index.tsx
- Enhancement
Add missing noTopLabel prop in TextBoxField
=> feat: add no top label on textbox

src/components/TextBoxField/index.tsx
- Enhancement
Forward prop unit and unitAlignement to TextBox 
1. Add props
=> feat: add unit prop

package.json, pnpm-lock.yaml, src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap, src/components/DateField/__tests__/__snapshots__/index.tsx.snap, src/components/DateField/index.tsx, src/components/RadioField/__tests__/__snapshots__/index.spec.tsx.snap, src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap, src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap
- Dependencies
Update scaleway UI/
=> fix: update scaleway ui v0.198.0

.storybook/preview.tsx, src/components/CheckboxField/index.tsx, src/components/DateField/index.tsx, src/components/Form/__stories__/Playground.stories.tsx, src/components/RadioField/index.tsx, src/components/RichSelectField/index.tsx, src/components/SelectNumberField/index.tsx, src/components/SelectableCardField/index.tsx, src/components/TagsField/index.tsx, src/components/TextBoxField/index.tsx, src/components/TimeField/index.tsx, src/components/ToggleField/index.tsx, src/hooks/useFormField.ts
- Feature
Disable field validation when the field is disabled
1. Handle disabled prop to remove validation on fields
Page | Before | After
:-   |  :-:   | -:
url | screenshot | screenshot
url | screenshot | screenshot
=> feat: disable field validation when the field is disabled

package.json, pnpm-lock.yaml, src/hooks/useValidation.ts, src/mocks/mockErrors.ts
=> chore(eslint): update eslint scaleway package

src/components/CheckboxField/__stories__/BooleanChecked.stories.tsx, src/components/CheckboxField/__stories__/Checked.stories.tsx, src/components/CheckboxField/__stories__/index.stories.tsx, src/components/CheckboxField/__tests__/index.spec.tsx, src/components/DateField/__stories__/index.stories.tsx, src/components/Form/__tests__/__snapshots__/index.spec.tsx.snap, src/components/Form/__tests__/index.spec.tsx, src/components/Form/index.tsx, src/components/RadioField/__stories__/Checked.stories.tsx, src/components/RadioField/__stories__/index.stories.tsx, src/components/RadioField/__tests__/index.spec.tsx, src/components/RichSelectField/__stories__/index.stories.tsx, src/components/SelectNumberField/__stories__/index.stories.tsx, src/components/SelectNumberField/__tests__/index.spec.tsx, src/components/SelectableCardField/__stories__/Checked.stories.tsx, src/components/SelectableCardField/__stories__/index.stories.tsx, src/components/SelectableCardField/__tests__/index.spec.tsx, src/components/Submit/__stories__/Invalid.stories.tsx, src/components/Submit/__stories__/Playground.stories.tsx, src/components/Submit/__stories__/Submitting.stories.tsx, src/components/Submit/__tests__/index.spec.tsx, src/components/SubmitErrorAlert/__stories__/Playground.stories.tsx, src/components/SubmitErrorAlert/__tests__/index.spec.tsx, src/components/TagsField/__stories__/index.stories.tsx, src/components/TextBoxField/__stories__/index.stories.tsx, src/components/TimeField/__stories__/index.stories.tsx, src/components/ToggleField/__stories__/index.stories.tsx, src/helpers/jestHelpers.tsx, src/hooks/__tests__/useFormField.spec.tsx, src/types.ts
=> feat: remove old onSubmit way of handling submit

package.json, pnpm-lock.yaml, src/components/DateField/__tests__/__snapshots__/index.tsx.snap, src/components/RichSelectField/__tests__/__snapshots__/index.spec.tsx.snap, src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap, src/components/TextBoxField/__tests__/__snapshots__/index.spec.tsx.snap, src/components/TimeField/__tests__/__snapshots__/index.spec.tsx.snap
- Migration
Bump to latest SWUI package
=> fix: bump swui and update tests
